apiVersion: v1
data:
{{- if or .Values.alertaConfig .Values.postgresql.enabled }}
  alertad.conf: |
    {{- if .Values.alertaConfig }}
    {{ range $key, $value := .Values.alertaConfig }}
    {{- /* The Python configuration file format is crazy. It needs single quote for all values, except boolean, number AND arrays!  */}}
    {{- if or (eq $value "True") (eq $value "False") (gt (int $value) 0 ) ( and (hasPrefix "[" $value ) (hasSuffix "]" $value ) ) }}
    {{ $key }} = {{ $value | nindent 4 | trim }}
    {{- else }}
    {{ $key }} = '{{ $value | nindent 4 | trim }}'
    {{- end }}
    {{- end }}
    {{- end }}
    {{ if .Values.postgresql.enabled -}}
    DATABASE_URL = "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
    {{- end }}
{{- end }}
{{- if .Values.alertaWebUIConfig }}
  config.js: |
{{ .Values.alertaWebUIConfig | indent 4 }}
{{- end }}
{{- if .Values.extraConfigs }}
{{- range .Values.extraConfigs }}
  {{ .subPath }}: |
{{ .data | indent 4 }}
{{- end }}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ include "alerta.fullname" . }}
  labels:
    app: {{ include "alerta.name" . }}
    chart: {{ include "alerta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
